### ISSUE TITLE
Related crate

### ISSUE THREAD

**Issue by saona-raimundo** [sigset/randomwalk#1]
Hi! I am the author of [markovian](https://crates.io/crates/markovian) and was very happy when I found your crate.

I wanted to ask you if we could collaborate in any way, or just leave open the option for the future. 

It seems to me that the goal of this crate is to simulate markovian stochastic processes in continuous time, where the "next" value depends only on the difference on time with the last value.

Cheers!

**Comment by 19h** [comment]
@saona-raimundo sorry! This notification most definitely went unnoticed.

I'd be very happy with collaboration!

**Comment by saona-raimundo** [comment]
Super! Thank you very much! 

I do not have any concrete idea in mind for the moment, but let's keep in touch.

**Comment by 19h** [comment]
We could merge the two crates and I’ll add you as a maintainer?

**Comment by saona-raimundo** [comment]
Are you thinking of creating a [workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) with both crates, or merging both in one crate?

Either way, we can start pointing out some design decisions we think we might encounter while merging both crates. Some of the things we might want to discuss are:
- RNGs in structs
  + Should they be arbitrary, public, only seedable?
- Next methods
  + Should we use the Iterator trait? 
  + What about variants of `next` like `next_interpolant`?
- State methods
  + Should we use a trait like [State](https://docs.rs/markovian/0.2.1/markovian/trait.State.html)?
  + Is it better to have a public field?
  + Or simply a method `set`?
- Traits
  + You do not seem to use many traits, do you think you would like to expose your `structs` with the traits I have come up with?
  + Is there a need for more/less traits?

**Comment by saona-raimundo** [comment]
We could continue talking at some point.
